/**
 * Delete seeded resources whose fixture no longer exists.
 *
 * Seeding is an upsert, so removing someone from board.ts or cohort.ts leaves their
 * resources behind in the project. Those orphans keep rendering — a patient deleted from
 * the fixtures still appears on the board, because the board is built from what is in
 * Medplum, not from what is in the source.
 *
 * Only touches resources carrying the SurgeryReady seed identifier whose key prefix is not
 * in the current fixtures. Everything it removes is regenerated by `npm run seed`.
 */
import type { Bundle, ResourceType } from '@medplum/fhirtypes';
import { BOARD } from './board.js';
import { login, medplum } from './client.js';
import { COHORT } from './recovery/cohort.js';
import { SYSTEM } from './systems.js';

const TYPES: ResourceType[] = [
  'Observation',
  'DiagnosticReport',
  'CoverageEligibilityResponse',
  'Coverage',
  'QuestionnaireResponse',
  'Task',
  'Appointment',
  'ServiceRequest',
  'Procedure',
  'Device',
  'Patient',
];

/** `maria-santos-session-3` belongs to `maria-santos`; `colin-reyes-…` belongs to nobody. */
function ownedBy(identifierValue: string, keys: Set<string>): boolean {
  for (const key of keys) {
    if (identifierValue === key || identifierValue.startsWith(`${key}-`)) {
      return true;
    }
  }
  return false;
}

async function main(): Promise<void> {
  await login();
  const keys = new Set([...BOARD.map((b) => b.key), ...COHORT.map((c) => c.key)]);
  const dryRun = !process.argv.includes('--delete');

  let orphans = 0;
  for (const type of TYPES) {
    const resources = await medplum.searchResources(
      type,
      `identifier=${encodeURIComponent(`${SYSTEM.seed}|`)}&_count=500`
    );
    for (const resource of resources) {
      const identifier = (resource as { identifier?: unknown }).identifier;
      const value = Array.isArray(identifier) ? identifier[0]?.value : (identifier as { value?: string } | undefined)?.value;
      if (!value || ownedBy(value, keys)) {
        continue;
      }
      orphans++;
      console.log(`${dryRun ? 'would delete' : 'deleting   '} ${type}/${resource.id}  (${value})`);
      if (!dryRun) {
        await medplum.deleteResource(type, resource.id as string);
      }
    }
  }

  if (orphans === 0) {
    console.log('No orphaned seed resources.');
  } else if (dryRun) {
    console.log(`\n${orphans} orphaned resources. Re-run with --delete to remove them.`);
  } else {
    console.log(`\nRemoved ${orphans} orphaned resources.`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

export type { Bundle };
