/**
 * Delete seeded resources whose fixture no longer exists.
 *
 * Seeding is an upsert, so removing someone from board.ts or cohort.ts leaves their
 * resources behind in the project. Those orphans keep rendering — a patient deleted from
 * the fixtures still appears on the board, because the board is built from what is in
 * Medplum, not from what is in the source.
 *
 * Only touches resources carrying the SurgeryReady seed identifier whose key prefix is not
 * in the current fixtures. Everything it removes is regenerated by `npm run seed`.
 */
import type { Bundle, ResourceType } from '@medplum/fhirtypes';
import { BOARD } from './board.js';
import { login, medplum } from './client.js';
import { COHORT, historyDays } from './recovery/cohort.js';
import { SYSTEM } from './systems.js';

const TYPES: ResourceType[] = [
  'Observation',
  'DiagnosticReport',
  'CoverageEligibilityResponse',
  'Coverage',
  'QuestionnaireResponse',
  'Task',
  'Appointment',
  'ServiceRequest',
  'Procedure',
  'Device',
  'Patient',
];

/**
 * Every identifier the current fixtures should produce.
 *
 * An exact allowlist rather than a key-prefix test, because shrinking the history window
 * orphans sessions belonging to patients who still exist: `ana-delgado-session-3` has a
 * living owner but no longer a valid day, and a prefix check waves it through.
 */
function validIdentifiers(): Set<string> {
  const valid = new Set<string>();

  for (const kase of BOARD) {
    valid.add(kase.key);
    for (const suffix of ['sr', 'appt', 'qr', 'task', 'coverage', 'eligibility']) {
      valid.add(`${kase.key}-${suffix}`);
    }
  }

  for (const patient of COHORT) {
    valid.add(patient.key);
    for (const suffix of ['procedure', 'insole', 'recovery-task', 'coverage', 'eligibility']) {
      valid.add(`${patient.key}-${suffix}`);
    }
    for (const day of historyDays(patient)) {
      valid.add(`${patient.key}-session-${day}`);
      valid.add(`${patient.key}-report-${day}`);
    }
  }

  return valid;
}

async function main(): Promise<void> {
  await login();
  const valid = validIdentifiers();
  const dryRun = !process.argv.includes('--delete');

  let orphans = 0;
  for (const type of TYPES) {
    const resources = await medplum.searchResources(
      type,
      `identifier=${encodeURIComponent(`${SYSTEM.seed}|`)}&_count=500`
    );
    for (const resource of resources) {
      const identifier = (resource as { identifier?: unknown }).identifier;
      const value = Array.isArray(identifier) ? identifier[0]?.value : (identifier as { value?: string } | undefined)?.value;
      if (!value || valid.has(value)) {
        continue;
      }
      orphans++;
      console.log(`${dryRun ? 'would delete' : 'deleting   '} ${type}/${resource.id}  (${value})`);
      if (!dryRun) {
        await medplum.deleteResource(type, resource.id as string);
      }
    }
  }

  if (orphans === 0) {
    console.log('No orphaned seed resources.');
  } else if (dryRun) {
    console.log(`\n${orphans} orphaned resources. Re-run with --delete to remove them.`);
  } else {
    console.log(`\nRemoved ${orphans} orphaned resources.`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

export type { Bundle };
